dataset:
  name: "custom"  # 或 "CIFAR10"
  augmentations: "resize"#["resize", "random_crop", "random_horizontal_flip", "auto_augment", "rand_augment"]
  use_normalize: true
  imgsize: 128
  crop_type: "random"  # 或 "center"
  batch_size: 32
  use_mixup: true
  use_cutmix: true

model:
  name: "resnet50"
  pretrained: true

training:
  epochs: 10
  optimizer: "Adam"
  lr: 0.001
  lr_decay:
    step_size: 7
    gamma: 0.1
  patience: 3
  seeds: [42, 43, 44]

evaluation:
  #num_classes: 2
  num_classes: 10
  #class_names: ["cat", "dog"]  # 根据实际类别名称填写
  class_names : ["airplane", "automobile", "bird", "cat", "deer", "dog", "frog", "horse", "ship", "truck"]
